create table hot_check_in (hot_check_in_id bigint(20) not null auto_increment, check_in_number varchar(50) not null, hot_reservation_id bigint(20), store_id int(11) not null, check_in_date date not null, from_date datetime null, to_date datetime null, duration_type varchar(20), duration_value double, transactor_id bigint(20), bill_transactor_id bigint(20), transaction_type_id int(11) not null, transaction_reason_id int(11) not null, transaction_ref varchar(100), transaction_comment varchar(255), transaction_user_detail_id int(11), add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, payment_status_code int(1) default 1, from_destination varchar(100), to_destination varchar(100), reservation_purpose varchar(100), item_id bigint(20) not null, hot_facility_room_id int(11), hot_facility_hall_id int(11), hot_facility_garden_id int(11), hot_facility_other_id int(11), unit_price double, unit_trade_discount double, unit_vat double, amount double, vat_rated varchar(10), vat_perc double, unit_price_inc_vat double, unit_price_exc_vat double, amount_inc_vat double, amount_exc_vat double, account_code varchar(20), narration varchar(100), total_std_vatable_amount double not null, total_zero_vatable_amount double not null, total_exempt_vatable_amount double not null, amount_tendered double, change_amount double, is_cash_discount_vat_liable varchar(3), acc_child_account_id int(11), currency_code varchar(10), xrate double, primary key (hot_check_in_id)) ENGINE=InnoDB;

create table hot_check_out (hot_check_out_id bigint(20) not null auto_increment, hot_check_in_id bigint(20) not null, check_out_number varchar(50) not null, store_id int(11) not null, check_out_date date not null, transaction_user_detail_id int(11), add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, bill_at_check_out double not null, paid_amount double not null, transaction_type_id int(11) not null, transaction_reason_id int(11) not null, primary key (hot_check_out_id)) ENGINE=InnoDB;

create table hot_facility_garden (hot_facility_garden_id int(11) not null auto_increment, garden_number varchar(50) not null, garden_description varchar(100) not null, availability_status_flag int(1) not null, functional_status_flag int(1) not null, house_keeping_status_flag int(1) not null, item_id bigint(20) not null, capacity int(5) not null, add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, primary key (hot_facility_garden_id)) ENGINE=InnoDB;

create table hot_facility_hall (hot_facility_hall_id int(11) not null auto_increment, hall_number varchar(50) not null, hall_description varchar(100) not null, availability_status_flag int(1) not null, functional_status_flag int(1) not null, house_keeping_status_flag int(1) not null, item_id bigint(20) not null, capacity int(5) not null, add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, primary key (hot_facility_hall_id)) ENGINE=InnoDB;

create table hot_facility_other (hot_facility_other_id int(11) not null auto_increment, facility_number varchar(50) not null, facility_description varchar(100) not null, availability_status_flag int(1) not null, functional_status_flag int(1) not null, house_keeping_status_flag int(1) not null, item_id bigint(20) not null, capacity int(5) not null, add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, primary key (hot_facility_other_id)) ENGINE=InnoDB;

create table hot_facility_room (hot_facility_room_id int(11) not null auto_increment, room_number varchar(50) not null, room_description varchar(100) not null, hot_room_category_id int(11) not null, availability_status_flag int(1) not null, functional_status_flag int(1) not null, house_keeping_status_flag int(1) not null, block_code varchar(20), level_code varchar(20), wing_code varchar(20), row_no varchar(5), col_no varchar(5), item_id bigint(20) not null, capacity int(5) default 1 not null, add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, primary key (hot_facility_room_id)) ENGINE=InnoDB;

create table hot_reservation (hot_reservation_id bigint(20) not null auto_increment, reservation_number varchar(50) not null, store_id int(11) not null, reservation_date date not null, from_date datetime null, to_date datetime null, duration_type varchar(20), duration_value double, transactor_id bigint(20), bill_transactor_id bigint(20), transaction_type_id int(11) not null, transaction_reason_id int(11) not null, transaction_ref varchar(100), transaction_comment varchar(255), transaction_user_detail_id int(11), add_user_detail_id int(11) not null, add_date datetime not null, edit_user_detail_id int(11), edit_date datetime null, reservation_status_code int(1), payment_status_code int(1) default 1, adults int(5), children int(5), no_rooms int(5), from_destination varchar(100), to_destination varchar(100), reservation_purpose varchar(100), sub_total double not null, total_trade_discount double not null, total_vat double not null, cash_discount double, grand_total double not null, total_std_vatable_amount double not null, total_zero_vatable_amount double not null, total_exempt_vatable_amount double not null, vat_perc double not null, amount_tendered double, change_amount double, is_cash_discount_vat_liable varchar(3), acc_child_account_id int(11), currency_code varchar(10), xrate double, primary key (hot_reservation_id)) ENGINE=InnoDB;

create table hot_reservation_facility (hot_reservation_facility_id bigint(20) not null auto_increment, item_id bigint(20) not null, hot_reservation_id bigint(20) not null, hot_facility_room_id int(11), hot_facility_hall_id int(11), hot_facility_garden_id int(11), hot_facility_other_id int(11), from_date datetime null, to_date datetime null, duration_type varchar(20), duration_value double, unit_price double, unit_trade_discount double, unit_vat double, amount double, vat_rated varchar(10), vat_perc double, unit_price_inc_vat double, unit_price_exc_vat double, amount_inc_vat double, amount_exc_vat double, account_code varchar(20), narration varchar(100), primary key (hot_reservation_facility_id)) ENGINE=InnoDB;
create table hot_room_category (hot_room_category_id int(11) not null auto_increment, category_name varchar(50), category_code varchar(10), primary key (hot_room_category_id)) ENGINE=InnoDB;
alter table hot_facility_room add constraint FKhot_facili885823 foreign key (hot_room_category_id) references hot_room_category (hot_room_category_id);
